
import Counter from '@/components/Counter/Counter';
import Link from 'next/link';
export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};
const HomePage = () => { 
  return (
    <div>
     <Counter/>
     <Link href={'/about'}>About</Link>
     <Link href={'/contact'}>Contact</Link>
    </div>
  );
};

export default HomePage;